spring.application.name=ProjetoSC

# habila o console web do h2 em http://localhost:8080/h2-console
spring.h2.console.enabled=true

# define a url fixa de acesso ao banco
# spring.datasource.url=jdbc:h2:mem:bdsptech

# habilita que os comandos sql sejam mostrados no log
spring.jpa.show-sql=true

# determina que os SQL do log sejam formatados
spring.jpa.properties.hibernate.format_sql=true

# permite que o data.sql seja executado no momento certos
spring.jpa.defer-datasource-initialization=true

# as duas linhas abaixo são para habilitar os detalhes dos erros de validação
server.error.include-message=always
server.error.include-binding-errors=always

# define o mysql como o banco de dados padr�o
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=#Sanguebom05
spring.datasource.url=jdbc:mysql://10.18.33.21:3306/eledoces
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.ddl-auto=update